services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuario
      MYSQL_DATABASE: Store
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

    deploy:
      resources:
        limits:
          memory: 256M

    mem_limit: 256m

volumes:
  db_data:
